### ISSUE TITLE
TF-IDF

### ISSUE THREAD

**Issue by jcai849** [jcai849/iNZightTA#10]
Add as another function

**Comment by bernicecu** [comment]
added. need to further inform user that required to add grouping variable, as this defines the documents. and check number of terms to visualize. should the graph be faceted by default?

**Comment by jcai849** [comment]
Great. Ideally yes, but not essential if it’s proving difficult

**Comment by bernicecu** [comment]
when user picks what variable to group by, plot is also automatically faceted by that var
